// Package handlers provides gRPC service handler implementations and proto conversions.
package handlers

import (
	"fmt"

	"microservice-template/internal/models"
	proto "microservice-template/protocols/userservice"
)

// UserToProto converts domain User to proto User.
// Returns nil if the input user is nil.
func UserToProto(user *models.User) *proto.User {
	if user == nil {
		return nil
	}

	return &proto.User{
		Uuid:      user.UUID.Bytes(),
		Email:     user.Email,
		Name:      user.Name,
		Status:    UserStatusToProto(user.Status),
		CreatedAt: user.CreatedAt.Unix(),
		UpdatedAt: user.UpdatedAt.Unix(),
	}
}

// UserStatusToProto converts domain UserStatus to proto UserStatus.
func UserStatusToProto(status models.UserStatus) proto.UserStatus {
	switch status {
	case models.UserActive:
		return proto.UserStatus_USER_STATUS_ACTIVE
	case models.UserDeleted:
		return proto.UserStatus_USER_STATUS_DELETED
	default:
		return proto.UserStatus_USER_STATUS_UNSPECIFIED
	}
}

// UserStatusFromProto converts proto UserStatus to domain UserStatus.
// Returns UserActive for UNSPECIFIED as a sensible default.
func UserStatusFromProto(status proto.UserStatus) (models.UserStatus, error) {
	switch status {
	case proto.UserStatus_USER_STATUS_ACTIVE:
		return models.UserActive, nil
	case proto.UserStatus_USER_STATUS_DELETED:
		return models.UserDeleted, nil
	case proto.UserStatus_USER_STATUS_UNSPECIFIED:
		return models.UserActive, nil // Default to active
	default:
		return 0, fmt.Errorf("unknown user status: %d", status)
	}
}

// CreateUserRequestToModel converts proto CreateUserRequest to domain User model.
// The returned User will have status set and basic fields populated.
// UUID and timestamps will be generated by the repository layer.
func CreateUserRequestToModel(req *proto.CreateUserRequest) (*models.User, error) {
	if req == nil {
		return nil, fmt.Errorf("create user request is nil")
	}

	return &models.User{
		Email: req.Email,
		Name:  req.Name,
	}, nil
}
